name: Testtaggert
favicon: null
layout_spectrum: 0.7345248940400779
typography_spectrum: 0.29272392811253667
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.07515184860676527
  lightness: 0.5920397895388305
  saturation: 0.5379511180799454
  rhythmicContrast: 0.41503987135365605
purpose: []
