name: Testtaggert
favicon: null
layout_spectrum: 0.33719
typography_spectrum: 0.11519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#070b17'
    - '#0444cb'
    - '#d44244'
    - '#049ef1'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
